FROM resin/%%RESIN_MACHINE_NAME%%-python:3-slim

#switch on systemd init system in container
ENV INITSYSTEM on

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY ./requirements.txt /requirements.txt
RUN READTHEDOCS=True pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN echo "*/5 * * * * /usr/src/app/start.sh" | crontab

CMD ["bash","start.sh"]

